---
name: "io_readbids"
description: Module reading bids specification for an input folder.
keywords:
  - Bids
  - Input
  - Structure
tools:
  - "scilpy":
      description: "The Sherbrooke Connectivity Imaging Lab (SCIL) Python dMRI processing toolbox."
      homepage: "https://github.com/scilus/scilpy.git"

input:
  - bids_folder:
      type: directory
      description: Folder containing bids file
      pattern: "*"

  - fs_folder:
      type: directory
      description: Folder containing fs file
      pattern: "*"

  - bids_ignore:
      type: file
      description: bids_ignore file
      pattern: "*.{bids_ignore}"

args:
  - readout:
      type: float
      description: Readout time to add in metadata.
      default: 0.062
  - clean_bids:
      type: boolean
      description: |
        If set to true, will remove participants with missing files
        from the final BIDS layout.
      default: false

output:
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

  - bidsstructure:
      type: file
      description: json file containing tractoflow bids structure
      pattern: "*.{json}"

authors:
  - "@harshana2011"
